name: test_conda
channels:
  - defaults
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - python=3.9
  - numpy
  - h5py
  - pandas
  - scipy
  - cctbx-base
  - hmmer
  - pyfastx
  - bokeh=2.4.3
  - pytorch
