name: test_conda
channels:
  - defaults
  - conda-forge
dependencies:
  - cctbx-base
  - python=3.9
  - pip
  - pip:
      - streamlit==1.11.0
      - pandas
      - numpy
      - scipy
      - tarfile
