name: test_conda
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - cctbx-base
  - scons
  - hmmer
  - python=3.9
  - pip
  - pip:
      - streamlit==1.11.0
      - pandas
      - numpy
      - scipy
      - git+https://gitlab.com/gchojnowski/findmysequence.git
